add podLabels - custom labels
traefik/traefik-helm-chart pull request #306
Opened 2020-11-13 13:43 UTC by m4r1u2

This PR will address adding custom labels to Pods, like the service.labels, until all labels are moved to _helper.tpl.

2020-11-13 13:46 UTC, wargamez approved these changes
Looking good

2020-11-19 12:16 UTC, SantoDE requested changes
This PR needs a minor version bump.

Can you also please add some unit tests for that?

2020-11-19 15:15 UTC, SantoDE requested changes
Nice. Thanks. 2 minor questions left

2020-11-19 15:15 UTC, SantoDE commented on traefik/tests/deployment-config_test.yaml
> +        imagePullSecrets:
What did change here?

2020-11-19 15:15 UTC, SantoDE commented on traefik/tests/deployment-config_test.yaml
> +        imagePullSecrets:
What did change here?

2020-11-19 15:25 UTC, m4r1u2 commented on traefik/tests/deployment-config_test.yaml
> +        imagePullSecrets:
It's a space at the end of the line.

2020-11-19 15:25 UTC, m4r1u2 commented on traefik/tests/deployment-config_test.yaml
> +        imagePullSecrets:
It's a space at the end of the line.

2020-11-20 11:13 UTC, SantoDE approved these changes
LGTM 👼

2020-11-20 11:14 UTC, merged