feat(healthchecksPort): as suggested by traefik/traefik-helm-chart#339
traefik/traefik-helm-chart pull request #353
Opened 2021-02-04 16:07 UTC by faust64

Allows to change liveness & readiness probes port, facilitating integration with GKE.

2021-03-02 11:18 UTC, SantoDE requested changes
Hey 👋 

Thanks for your PR :)

Can we please have a simple unit test testing the new configuration? Also, this PR needs a version bump.

Let me know if something is not clear please :)

2021-03-02 11:18 UTC, SantoDE commented on traefik/Chart.yaml
> +version: 9.14.4
needs a proper version

2021-03-02 15:05 UTC, faust64 commented on traefik/Chart.yaml
> +version: 9.14.4
already have a 9.15.5 somewhere. 9.15.6? Otherwise let me know.

2021-03-10 09:25 UTC, SantoDE approved these changes
LGTM

2021-03-10 10:00 UTC, SantoDE commented
Im super sorry, but our tooling won't merge PR's from your organization account (even when we accept the invite).

Can you redo them on your personal account?

2021-03-10 10:46 UTC, ldez commented
Could you keep this PR open I will try something with our bot? thank you

2021-03-10 10:51 UTC, faust64 commented
See #391

2021-03-10 10:52 UTC, faust64 commented
Sure, re-opening

2021-03-10 12:56 UTC, merged

2021-03-10 13:01 UTC, ldez commented
I learned to the bot how to handle this kind of PR, so, good news, now we can easily handle PR from an organization.

2021-03-10 13:07 UTC, faust64 commented
Checking the diff, is it normal the keywords array was removed over there:

https://github.com/traefik/traefik-helm-chart/pull/353/files#diff-ba22aa51b44ab3feb99c9b7cba4dfad404398576b6b7e64b6df8307d3c406304L7

2021-03-10 13:11 UTC, ldez commented
it's not expected, related to f5b28e5.

2021-03-10 13:19 UTC, faust64 commented
While I'm still here, opening a new PR restoring those keywords: https://github.com/traefik/traefik-helm-chart/pull/392
Though you're maybe already fixing it ...