fix(tags): handle non-semvers tag, as discussed in #321
traefik/traefik-helm-chart pull request #360
Opened 2021-02-16 07:46 UTC by faust64

Ensures IngressClass installation check would properly handle deployment for traefik `latest` tag.

2021-03-02 09:18 UTC, SantoDE commented
Hey @faust64,

can you bump the version again please? I would do so, but looks like you did not allow edits from maintainers :)

2021-03-02 09:18 UTC, SantoDE requested changes
See above

2021-03-02 09:18 UTC, SantoDE commented on traefik/Chart.yaml
> +version: 9.14.4
Needs to be 9.15.5

2021-03-02 14:22 UTC, SantoDE reviewed
LGTM. Thanks!

2021-03-02 14:23 UTC, SantoDE approved these changes
LGTM

2021-03-03 11:31 UTC, SantoDE commented
Hey @faust64,

can you please provide maintainers with permissions to do edits on that PR? That would help a lot.

Thanks!

2021-03-03 12:00 UTC, faust64 commented
I'm not sure I can. AFAIU, there should be a button on under the Unsubscribe one, in that pull request ( https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork )

I can't find it, not sure why:
![unsubscribe-btn](https://user-images.githubusercontent.com/211675/109802552-426a6a00-7c20-11eb-935b-8f1ab8866c06.png)

let me know if there's anything I can do.

2021-03-05 16:05 UTC, SantoDE commented
Somehow, I cant push to your branch. No matter what I try.

Can you open the PR (check the box) to allow edits from maintainer? :)

2021-03-05 16:17 UTC, faust64 commented
Sorry, as stated earlier, I don't see that checkbox. This seems to be due to my forking to my organization instead of my own account. I can re-open my PRs, forking again, if there's no way around this.

2021-03-05 16:23 UTC, faust64 commented
see https://github.com/traefik/traefik-helm-chart/pull/384

2021-03-05 16:23 UTC, closed without merging