feat(labelSelector): option matching Ingresses based on labelSelectors
traefik/traefik-helm-chart pull request #361
Opened 2021-02-16 08:17 UTC by faust64

as suggested in https://github.com/traefik/traefik-helm-chart/issues/264
traefik can pick Ingress objects based on a labelSelector.
This can be useful in larger clusters, when ingress are dedicated to an environment (prod, stage, ...), when SDN is broken into security zones with dedicated ingresses, ...

2021-03-02 09:14 UTC, SantoDE commented
Hey @faust64,

can we have some quick unit tests for that please? :)

2021-03-02 14:57 UTC, SantoDE requested changes
One last step

2021-03-02 14:57 UTC, SantoDE commented on traefik/Chart.yaml
> +version: 9.15.5
9.16.0 plx :)

2021-03-02 15:03 UTC, faust64 commented on traefik/Chart.yaml
> +version: 9.15.5
:+1:

2021-03-10 10:46 UTC, faust64 commented
See #390

2021-03-10 10:46 UTC, closed without merging