Update default HPA API Version to `v2` and add support for behavior
traefik/traefik-helm-chart pull request #518
Opened 2021-10-29 06:40 UTC by grieshaber

### What does this PR do?

This MR updates the API-Version of the hpa to autoscaling/v2beta2. Since k8s 1.18, this api-version adds support for custom scaling behavior. Therefore i added some example values and the corresponding property in hpa.yaml.

### Motivation
Requested by @Xyaren in #515

### More

- [X] Yes, I updated the [chart version](https://github.com/traefik/traefik-helm-chart/blob/9b32ed1b414cc0be1ad46bcb335fcfc93ded06f3/traefik/Chart.yaml#L5)

### Additional Notes

I wrapped the behavior property in the hpa in an additional if clause, because it is only supported in clusters >= 1.18, so it won't break things and needs to be enabled explicitly.

2021-11-30 12:46 UTC, junaid-ali commented
@kevinpollet any update on this one, could you please have a look at this again?

2022-01-24 16:27 UTC, cilindrox commented
this is also relevant since v2beta2 allows specifying multiple metrics for the HPA to scale on. Right now we're constrained to a single metric.

2022-01-25 06:42 UTC, grieshaber commented
I rebased my branch to the latest changes and would appreciate someone having a look at this PR.

2022-10-04 07:18 UTC, jburke-godaddy requested changes

2022-10-04 07:18 UTC, jburke-godaddy commented on traefik/templates/hpa.yaml
> +apiVersion: autoscaling/v2beta2
```suggestion
{{- if .Capabilities.APIVersions.Has "autoscaling/v2beta2/HorizontalPodAutoscaler" }}
apiVersion: autoscaling/v2beta2
{{- else if .Capabilities.APIVersions.Has "autoscaling/v2beta1/HorizontalPodAutoscaler" }}
apiVersion: autoscaling/v2beta1
{{- else }}
{{- fail "\n\n ERROR: You must have at least autoscaling/v2beta1 to use HorizontalPodAutoscaler" }}
{{- end }}
```
Similar adaption is in: https://github.com/traefik/traefik-helm-chart/blob/859adf66447d8242ae6c697fc901473d4684c282/traefik/templates/ingressclass.yaml#L2-L10

This code should allow the template to adapt to older versions.

2022-10-06 08:34 UTC, merged

2022-11-02 06:59 UTC, mrx88 commented
FYI - maybe due to helm version problems (did not verify),  but this part is not rendering correctly when using the example configuration with Helm v3.10.1:
```
{{- if .Values.autoscaling.behavior }}
  behaviour: 
{{ toYaml .Values.autoscaling.behavior | indent 4 }}
{{- end }}
```
Output is:
```
 behavior:
    scaleDown:
      policies:
      - periodSeconds: 60
        type: Pods
        value: 1
      stabilizationWindowSeconds: 300
```

but should be:
```
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
```
(Note the -type is missing).

2022-11-02 08:28 UTC, mloiseleur commented
Hello @mrx88,

There is `type: Pods` in the output. It's expected (and alphabetically ordered) output. 
In this example, `periodSeconds`, `type` and `value` are part of the same policy. It doesn't matter if `periodSeconds` is before or after `type` as long as they are in the same policy.

2022-11-02 08:33 UTC, mrx88 commented
> Hello @mrx88,
> 
> There is `type: Pods` in the output. It's expected (and alphabetically ordered) output. In this example, `periodSeconds`, `type` and `value` are part of the same policy. It doesn't matter if `periodSeconds` is before or after `type` as long as they are in the same policy.

I was pointing out to "-" char missing for Type, but if it works that way too then no worries ;)