fix(#521): adds allowExternalNameServices to KubernetesIngress provider
traefik/traefik-helm-chart pull request #529
Opened 2021-12-05 10:05 UTC by faust64

### What does this PR do?

Adds a missing option (providers.kubernetesingress.allowExternalNameServices)

### Motivation

As reported by @oskapt : #521

### More

- [X] Yes, I updated the [chart version](https://github.com/traefik/traefik-helm-chart/blob/9b32ed1b414cc0be1ad46bcb335fcfc93ded06f3/traefik/Chart.yaml#L5)

### Additional Notes

N/A

2021-12-06 13:13 UTC, kevinpollet commented
Hello @faust64 and thanks for your pull request,

I think the chart version should be `10.7.0` as this PR is an enhancement.

Could you also add some tests?

2021-12-11 19:02 UTC, gretel commented
works for me:

```
time="2021-12-11T19:01:25Z" level=warning msg="ExternalName service loading is enabled, please ensure that this is expected (see AllowExternalNameServices option)" providerName=kubernetescrd
time="2021-12-11T19:01:25Z" level=warning msg="ExternalName service loading is enabled, please ensure that this is expected (see AllowExternalNameServices option)" providerName=kubernetes
```

2021-12-17 16:10 UTC, kevinpollet requested changes

2021-12-17 16:10 UTC, kevinpollet commented on traefik/tests/traefik-config_test.yaml
> +  - it: should allow external name services when specified in configuration
Can you merge this test with the one above, instead of duplicating it?

2021-12-20 13:32 UTC, kevinpollet commented
Superseded by #533

2021-12-20 13:32 UTC, closed without merging