Added volumeName to PersistentVolumeClaim
traefik/traefik-helm-chart pull request #792
Opened 2023-02-13 08:45 UTC by TBurda

### What does this PR do?

Added volumeName to PersistentVolumeClaim.

2023-02-13 08:54 UTC, mloiseleur requested changes
Thanks @TBurda for this PR. 
Would you please update tests accordingly ?

2023-02-13 09:53 UTC, TBurda commented
Hi @mloiseleur, tests updated.

2023-02-14 08:45 UTC, mloiseleur approved these changes
Thanks @TBurda !

2023-02-14 09:04 UTC, mloiseleur approved these changes

2023-02-14 09:05 UTC, charlie-haley approved these changes

2023-02-14 09:06 UTC, merged