Add support for running the dashboard as ingress
traefik/traefik-helm-chart pull request #879
Opened 2023-06-28 06:37 UTC by davhdavh

### What does this PR do?

Add support for running the dashboard as ingress
Add documentation for why this may be desired
Add documentation for how to get external ip and loadbalancer ip working in own vm/hardware

### Motivation

Add some extra documentation for how to get started with traefik on a bare k8s cluster.
Easier support for ingress access to the dashboard
Implicit documentation of how to use Ingress with attributes (something the traefik docs are quite bad at showing)

### More

- [x] Yes, I updated the tests accordingly

2023-06-28 07:35 UTC, mloiseleur requested changes
Thanks for this other PR @davhdavh 
Interesting. I have two main comments:
1. We have moved all example to EXAMPLES.md, wdyt about add your example in this file ?
2. `api.insecure` is not linked to port. So this should be put elsewhere.

2023-06-28 09:05 UTC, davhdavh commented
> api.insecure is not linked to port. So this should be put elsewhere.

https://doc.traefik.io/traefik/v3.0/operations/api/#insecure
Well, port and entryPoint is used intermixed in the helm config, but this binds specifically to the `traefik` entryPoint, and that is configured in ports.traefik. So yes I think it very much belongs here

2023-06-28 09:09 UTC, davhdavh commented
> We have moved all example to EXAMPLES.md, wdyt about add your example in this file ?

Primarily because the main place to read the documentation does not have the examples accessible:
https://artifacthub.io/packages/helm/traefik/traefik

2023-07-12 09:31 UTC, darkweaver87 commented on traefik/values.yaml
> +    # but you might need it as an ingress rather than ingressRoute, and this would allow you to do so
Well the ingress method works but is a bit hacky.

2023-07-12 09:31 UTC, darkweaver87 commented on traefik/values.yaml
> +    # The creation of the secret resource "dashboard-auth" is left to the reader (it needs username and password fields)
```suggestion
    # The creation of the secret resource "dashboard-auth" is left to the reader (it needs username and password fields). You may prefer better authentication method like OIDC.
```

2023-07-12 09:31 UTC, darkweaver87 commented
> > api.insecure is not linked to port. So this should be put elsewhere.
> 
> https://doc.traefik.io/traefik/v3.0/operations/api/#insecure Well, port and entryPoint is used intermixed in the helm config, but this binds specifically to the `traefik` entryPoint, and that is configured in ports.traefik. So yes I think it very much belongs here

Well yes and no ;-) 

I would tend to agree with @mloiseleur. `api.insecure` is not in `entrypoints` section of traefik configuration and `ports` tries to stick as much as possible at it  whereas `api.insecure` deals with `routers`.

2023-08-10 09:09 UTC, mloiseleur commented
@davhdavh Will you update this PR or should we close it ?

2023-08-13 04:09 UTC, closed without merging